### PR TITLE
MQE-2247: Implement additional <section> and <operation> entity use cases in SVC tool

### PR DESCRIPTION
**Pull request by soumyau**
# Description (*)

added <section> entity use cases
added <operation> use cases
merge https://github.com/magento-pangolin/magento-semver/pull/2 before reviewing this. (commits are on top of that branch)

## Fixed Issues (if relevant)

1. magento/magento-semver#<issue_number>: Issue title

## Manual testing scenarios (*)

1. ...

2. ...

## Contribution checklist (*)

- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tomreece** [comment]
When I run the comparison against an identical before and after, I get thousands of results on various Meta.xml files:
https://pastebin.com/zYm3aLMa

**Comment by soumyau** [comment]
> When I run the comparison against an identical before and after, I get thousands of results on various Meta.xml files:
> https://pastebin.com/zYm3aLMa

Fixed

**Comment by tomreece** [comment]
Adding `parameterized="true"` to an `<element>` does not result in a MAJOR change notice.

**Comment by soumyau** [comment]
> Adding `parameterized="true"` to an `<element>` does not result in a MAJOR change notice.

good catch, fixed.

**Review by tomreece — APPROVED** [review]
Looks good to me.

**Pull request merged**
